// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "bandome.h"
#include <stdio.h>
#include <string>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <FL/Fl_Input_.H>
#include <cmath>
#include <cstdlib>
#include <vector>
#include <stdlib.h>
#include<time.h>

using namespace std;
Fl_Window *G_win;
Fl_Wizard *G_wiz;

Fl_Group *g;
Fl_Group *g2;
Fl_Group *g3;
Fl_Group *g4;
Fl_Group *g5;
Fl_Group *g6;
Fl_Group *g7;
Fl_Group *g8;

Fl_Box *h;
Fl_Box *j;
Fl_Box *jo;
Fl_Box *x;
Fl_Box *letterin;
Fl_Box *liko;
Fl_Box *result;
Fl_Box *uzrasas1;
Fl_Box *ivesti1;
Fl_Box *spej1;
Fl_Box *rez1;
Fl_Box *uzrasas;
Fl_Box *ivesti;
Fl_Box *spej;
Fl_Box *rez;
Fl_Box *z;
Fl_Box *result1;
Fl_Box *yy;
Fl_Box *vv;
Fl_Box *uu;
Fl_Box *ss;
Fl_Box *rr;
Fl_Box *qq;

Fl_Input *name;
Fl_Input *linput;
Fl_Input *raidein;
Fl_Input *raideinn;

Fl_Output *resultout;
Fl_Output *guessout;
Fl_Output *tt;
Fl_Output *letter1;
Fl_Output *letter2;
Fl_Output *letter3;
Fl_Output *letter4;
Fl_Output *letter5;
Fl_Output *letter6;
Fl_Output *letter7;
Fl_Output *letter8;
Fl_Output *letter9;
Fl_Output *letter10;
Fl_Output *letter11;
Fl_Output *letter12;
Fl_Output *letter13;
Fl_Output *letter14;
Fl_Output *letter15;
Fl_Output *letter16;
Fl_Output *letter17;
Fl_Output *letter18;
Fl_Output *letter19;
Fl_Output *letter20;
Fl_Output *letter21;
Fl_Output *letter22;
Fl_Output *letter23;
Fl_Output *letter24;
Fl_Output *letter25;
Fl_Output *letter26;
Fl_Output *raide14;
Fl_Output *raide24;
Fl_Output *raide34;
Fl_Output *raide44;
Fl_Output *rezout1;
Fl_Output *spejout1;
Fl_Output *wraid1;
Fl_Output *vraid1;
Fl_Output *uraid1;
Fl_Output *oraid1;
Fl_Output *praid1;
Fl_Output *rraid1;
Fl_Output *sraid1;
Fl_Output *traid1;
Fl_Output *qraid1;
Fl_Output *yraid1;
Fl_Output *eraid1;
Fl_Output *graid1;
Fl_Output *hraid1;
Fl_Output *xraid1;
Fl_Output *nraid1;
Fl_Output *zraid1;
Fl_Output *mraid1;
Fl_Output *araid1;
Fl_Output *braid1;
Fl_Output *craid1;
Fl_Output *draid1;
Fl_Output *fraide;
Fl_Output *iraid1;
Fl_Output *jraid1;
Fl_Output *kraid1;
Fl_Output *lraid1;
Fl_Output *pirmspej1;
Fl_Output *antraspej1;
Fl_Output *treciaspej1;
Fl_Output *ketvirtaspej1;
Fl_Output *penktaspej1;
Fl_Output *rezout;
Fl_Output *spejout;
Fl_Output *wraid;
Fl_Output *vraid;
Fl_Output *uraid;
Fl_Output *oraid;
Fl_Output *praid;
Fl_Output *rraid;
Fl_Output *sraid;
Fl_Output *traid;
Fl_Output *qraid;
Fl_Output *yraid;
Fl_Output *eraid;
Fl_Output *graid;
Fl_Output *hraid;
Fl_Output *xraid;
Fl_Output *nraid;
Fl_Output *zraid;
Fl_Output *mraid;
Fl_Output *araid;
Fl_Output *braid;
Fl_Output *craid;
Fl_Output *draid;
Fl_Output *fraid;
Fl_Output *iraid;
Fl_Output *jraid;
Fl_Output *kraid;
Fl_Output *lraid;
Fl_Output *pirmspej;
Fl_Output *antraspej;
Fl_Output *treciaspej;
Fl_Output *ketvirtaspej;
Fl_Output *penktaspej;
Fl_Output *sestaspej;
Fl_Output *septintaspej;
Fl_Output *task;
Fl_Output *lala;
Fl_Output *pp;
Fl_Output *oo;
Fl_Output *nn;
Fl_Output *mm;
Fl_Output *ll;
Fl_Output *kk;
Fl_Output *jj;
Fl_Output *ii;
Fl_Output *hh;
Fl_Output *gg;
Fl_Output *ff;
Fl_Output *ee;
Fl_Output *dd;
Fl_Output *cc;
Fl_Output *bb;
Fl_Output *aa;
Fl_Output *zzz;
Fl_Output *yyy;
Fl_Output *xxx;
Fl_Output *zinute;

Fl_Button *vvv;
Fl_Button *easy;
Fl_Button *medium;
Fl_Button *hard;
Fl_Button *next1;
Fl_Button *m;
Fl_Button *y;
Fl_Button *tol1;
Fl_Button *tol;
Fl_Button *top;
Fl_Button *contin;
Fl_Button *iseiti;
Fl_Button *xx;
Fl_Button *ww;
Fl_Button *ok;



void next_cb(Fl_Widget*, void*) {
	G_wiz->next();
}

void done_cb(Fl_Widget*, void*) {
	exit(0);
}

void back_cb(Fl_Widget*, void*) {
	G_wiz->prev();
}

void easyButton_cb(Fl_Widget*, void*) {
	G_wiz->value(g3);
}

void mediumButton_cb(Fl_Widget*, void*) {
	G_wiz->value(g4);
}

void hardButton_cb(Fl_Widget*, void*) {
	G_wiz->value(g5);
}

void isnaujo_cb(Fl_Widget*,void*) {
     G_wiz->value(g);
}

void geriausiulentele_cb(Fl_Widget*,void*) {
     G_wiz->value(g8);
}

void geriausiulentelegrizti_cb(Fl_Widget*, void*) {
	G_wiz->value(g6);
}

void rasymasVardu_cb(Fl_Widget* w, void* param) {

	string Vardai[100];
	skaitymasVardu(Vardai);
	Informacija* musuInfo = reinterpret_cast<Informacija*>(param);
	ofstream fout(musuInfo->failas.c_str(), ios_base::app);

	if (!fout)
		printf("Failas neegzistuoja");

	for (int i = 0; i < 100; i++)
	{
		if (musuInfo->name->value() == Vardai[i])
	    {
		zinute->value("Toks vardas jau yra sukurtas, prasome pasirinkti kita varda");
		fout.close();
		return;
	    }
	}

		zinute->value("Sveiki atvyke i Kartuves!");
		fout << musuInfo->name->value() << std::endl;
		next1->show();

	fout.close();
}

void skaitymasVardu(string Vardai[]) {

	ifstream fd("vardai.txt");
	if (!fd)
		printf("Failas neegzistuoja");
	else
		fd.ignore(80, '\n');
	for (int i = 0; i < 100; i++)
	{
		getline(fd, Vardai[i]);
	}


	fd.close();
}

void skaitymasZodis_4(string Zodis_4[], string &zodis_4){

	vector<string> words;
	ifstream file("letter_4.txt");
	string line;
	if (!file)
		printf("Failas neegzistuoja");
	else
		while (getline(file, line))
		{
			words.push_back(line);
			srand(time(0));
		}

	zodis_4  = words[rand() % words.size()];
	file.close();
}

void skaitymasZodis_5(string Zodis_5[], string &zodis_5) {

	vector<string> words;
	ifstream fil("letter_5.txt");
	string line;
	if (!fil)
		printf("Failas neegzistuoja");
	else
		while (getline(fil, line))
		{
			words.push_back(line);
			srand(time(0));
		}

	zodis_5 = words[rand() % words.size()];
	fil.close();
}

void skaitymasZodis_7(string Zodis_7[], string &zodis_7) {

	vector<string> words;
	ifstream fill("letter_7.txt");
	string line;
	if (!fill)
		printf("Failas neegzistuoja");
	else
		while (getline(fill, line))
		{
			words.push_back(line);
			srand(time(0));
		}

	zodis_7 = words[rand() % words.size()];
	fill.close();
}





void gaminkRaides(string zodis_4, vector<string>& raides){

    string Zodis_4[150];
	skaitymasZodis_5(Zodis_4, zodis_4);
    int l = zodis_4.length();
    char z[] = " ";
    for (int i=0;i<l;i++){
       z[0] = zodis_4[i];
       raides.push_back(string(z));
    }
    }


void spausdinkRaides(vector<string>& raides){

    int l = raides.size();
    for (int i=0;i<l;i++)
       cout << raides[i] <<endl;
    }

/*
void konvertavimas_4(string zodis_4, char word_4[] ){

	string Zodis_4[150];
	skaitymasZodis_4(Zodis_4,zodis_4);
	int n = zodis_4.length();
    word_4[n];
	strcpy(word_4, zodis_4.c_str());
	 for(int i=0; i<n; i++)
     {
       cout << word_4[i] <<endl;
     }
}
*/
void konvertavimas_5(string zodis_5, char word_5[]) {

	string Zodis_5[1500];
	skaitymasZodis_5(Zodis_5, zodis_5);
	int n = zodis_5.length();
	word_5[n];
	strcpy(word_5, zodis_5.c_str());
}

void konvertavimas_7(string zodis_7, char word_7[]) {

	string Zodis_7[150];
	skaitymasZodis_7(Zodis_7, zodis_7);
	int n = zodis_7.length();
	word_7[n];
	strcpy(word_7, zodis_7.c_str());
}

int main(int argc, char** argv) {
	G_win = new Fl_Window(715, 555, "KARTUV\304\226S");
	G_wiz = new Fl_Wizard(0, 0, 715, 555);

	Informacija ivestis;
	Informacija skaitymas;
	ivestis.failas = "vardai.txt";
	skaitymas.failas = "vardai.txt";
	Zodynelis skaitymas_4;
	Zodynelis skaitymas_5;
	Zodynelis skaitymas_7;
	skaitymas_4.failas_4 = "letter_4.txt";
	skaitymas_5.failas_5 = "letter_5.txt";
	skaitymas_7.failas_7 = "letter_7.txt";



	//pagrindinispuslapis
	{

		g = new Fl_Group(0, 0, 715, 555);
		g->color((Fl_Color)246);

        jo = new Fl_Box(265, 159, 180, 101, "\304\256ra\305\241ykite vard\304\205:");
		jo->labeltype(FL_EMBOSSED_LABEL);
		jo->labelsize(40);

		ivestis.name = new Fl_Input(255, 250, 180, 45);
		ivestis.name->box(FL_EMBOSSED_BOX);
		ivestis.name->tooltip();

		next1 = new Fl_Button(585, 500, 110, 30, "Eiti toliau");
		next1->color((Fl_Color)55);
		next1->selection_color(FL_GRAY0);
		next1->labeltype(FL_EMBOSSED_LABEL);
		next1->labelcolor(FL_GRAY0);
		next1->callback((Fl_Callback*)next_cb);
		next1->align(Fl_Align(FL_ALIGN_WRAP));
		next1->hide();

		ok = new Fl_Button(465, 250, 95, 45, "OK");
		ok->color((Fl_Color)55);
		ok->selection_color(FL_GRAY0);
		ok->labeltype(FL_EMBOSSED_LABEL);
		ok->labelcolor(FL_GRAY0);
		ok->align(Fl_Align(FL_ALIGN_WRAP));
		ok->callback(rasymasVardu_cb, &ivestis);

		zinute = new Fl_Output(120, 325, 435, 30);
		zinute->color((Fl_Color)246);

		h = new Fl_Box(205, 18, 295, 102, "KARTUV\304\226S");
		h->labeltype(FL_SHADOW_LABEL);
		h->labelsize(49);

		g->end();
	}


	//2 puslapis player 1

	{
		g2 = new Fl_Group(0, 0, 715, 555);
		g2->color((Fl_Color)246);

		easy = new Fl_Button(165, 280, 95, 50, "lengvas           (4 raid\304\227s)");
		easy->color((Fl_Color)55);
		easy->selection_color(FL_GRAY0);
		easy->labeltype(FL_EMBOSSED_LABEL);
		easy->labelcolor(FL_GRAY0);
		easy->align(Fl_Align(FL_ALIGN_WRAP));
		easy->callback(easyButton_cb);
		easy->type(FL_RADIO_BUTTON);

	    medium = new Fl_Button(295, 280, 95, 50, "vidutinis       (5 raid\304\227s)");
		medium->color((Fl_Color)55);
		medium->selection_color(FL_GRAY0);
		medium->labeltype(FL_EMBOSSED_LABEL);
		medium->labelcolor(FL_GRAY0);
		medium->align(Fl_Align(FL_ALIGN_WRAP));
		medium->type(FL_RADIO_BUTTON);
		medium->callback(mediumButton_cb);

		hard = new Fl_Button(420, 280, 95, 50, "sunkus         (7 raid\304\227s)");
		hard->color((Fl_Color)55);
		hard->selection_color(FL_GRAY0);
		hard->labeltype(FL_EMBOSSED_LABEL);
		hard->labelcolor(FL_GRAY0);
		hard->align(Fl_Align(FL_ALIGN_WRAP));
        hard->type(FL_RADIO_BUTTON);
        hard->callback(hardButton_cb);

		j = new Fl_Box(200, 193, 275, 77, "Pasirinkite \305\276od\305\276io sunkum\304\205");
		j->labeltype(FL_SHADOW_LABEL);
		j->labelsize(30);

		g2->end();
	}



	//pats zaidimo ekranas 4 RAIDEM
	{
		g3 = new Fl_Group(0, 0, 715, 555);
		g3->color((Fl_Color)246);

		x = new Fl_Box(200, 8, 295, 102, "KARTUV\304\226S");
		x->labeltype(FL_SHADOW_LABEL);
		x->labelsize(49);

		y = new Fl_Button(585, 500, 110, 30, "Toliau");
		y->color((Fl_Color)55);
		y->selection_color(FL_GRAY0);
		y->labeltype(FL_EMBOSSED_LABEL);
		y->labelcolor(FL_GRAY0);
		y->callback((Fl_Callback*)next_cb);
		y->align(Fl_Align(FL_ALIGN_WRAP));

		letterin = new Fl_Box(340, 259, 30, 16, "\304\256veskite raid\304\231");
		letterin->labeltype(FL_EMBOSSED_LABEL);
		letterin->labelsize(25);

		linput = new Fl_Input(285, 296, 150, 29);//raides ivedimas


		liko = new Fl_Box(85, 448, 35, 17, "Liko sp\304\227jim\305\263:");
		liko->labelsize(20);

		result = new Fl_Box(305, 448, 35, 17, "Rezultas:");
		result->labelsize(20);

		resultout = new Fl_Output(285, 475, 70, 35); //rezultato isvedimas
		resultout->color((Fl_Color)246);

		guessout = new Fl_Output(75, 475, 70, 35);//spejimolikucio isvedimas
		guessout->color((Fl_Color)246);
		//raidziu sarasas
		letter1 = new Fl_Output(560, 400, 30, 30);
		letter1->color((Fl_Color)246);
		letter1->insert("w");

		letter2 = new Fl_Output(525, 400, 30, 30);
		letter2->color((Fl_Color)246);
		letter2->insert("v");

		letter3 = new Fl_Output(490, 400, 30, 30);
		letter3->color((Fl_Color)246);
		letter3->insert("u");

		letter4 = new Fl_Output(280, 400, 30, 30);
		letter4->color((Fl_Color)246);
		letter4->insert("o");

		letter5 = new Fl_Output(315, 400, 30, 30);
		letter5->color((Fl_Color)246);
		letter5->insert("p");

		letter6 = new Fl_Output(385, 400, 30, 30);
		letter6->color((Fl_Color)246);
		letter6->insert("r");

		letter7 = new Fl_Output(420, 400, 30, 30);
		letter7->color((Fl_Color)246);
		letter7->insert("s");

		letter8 = new Fl_Output(455, 400, 30, 30);
		letter8->color((Fl_Color)246);
		letter8->insert("t");

		letter9 = new Fl_Output(350, 400, 30, 30);
		letter9->color((Fl_Color)246);
		letter9->insert("q");

		letter10 = new Fl_Output(630, 400, 30, 30);
		letter10->color((Fl_Color)246);
		letter10->insert("y");

		letter11 = new Fl_Output(385, 365, 30, 30);
		letter11->color((Fl_Color)246);
		letter11->insert("e");

		letter12 = new Fl_Output(455, 365, 30, 30);
		letter12->color((Fl_Color)246);
		letter12->insert("g");

		letter13 = new Fl_Output(490, 365, 30, 30);
		letter13->color((Fl_Color)246);
		letter13->insert("h");

		letter14 = new Fl_Output(595, 400, 30, 30);
		letter14->color((Fl_Color)246);
		letter14->insert("x");

		letter15 = new Fl_Output(245, 400, 30, 30);
		letter15->color((Fl_Color)246);
		letter15->insert("n");

		letter16 = new Fl_Output(665, 400, 30, 30);
		letter16->color((Fl_Color)246);
		letter16->insert("z");

		letter17 = new Fl_Output(665, 365, 30, 30);
		letter17->color((Fl_Color)246);
		letter17->insert("m");

		letter18 = new Fl_Output(245, 365, 30, 30);
		letter18->color((Fl_Color)246);
		letter18->insert("a");

		letter19 = new Fl_Output(280, 365, 30, 30);
		letter19->color((Fl_Color)246);
		letter19->insert("b");

		letter20 = new Fl_Output(315, 365, 30, 30);
		letter20->color((Fl_Color)246);
		letter20->insert("c");

		letter21 = new Fl_Output(350, 365, 30, 30);
		letter21->color((Fl_Color)246);
		letter21->insert("d");

		letter22 = new Fl_Output(420, 365, 30, 30);
		letter22->color((Fl_Color)246);
		letter22->insert("f");

		letter23 = new Fl_Output(525, 365, 30, 30);
		letter23->color((Fl_Color)246);
		letter23->insert("i");


		letter24 = new Fl_Output(560, 365, 30, 30);
		letter24->color((Fl_Color)246);
		letter24->insert("j");

		letter25 = new Fl_Output(595, 365, 30, 30);
		letter25->color((Fl_Color)246);
		letter25->insert("k");

		letter26 = new Fl_Output(630, 365, 30, 30);
		letter26->color((Fl_Color)246);
		letter26->insert("l");

		raide14 = new Fl_Output(280, 190, 30, 30);//1 spejimo raide
		raide14->color((Fl_Color)246);

        string name;
        vector<string> rd;
        gaminkRaides(name, rd);
        spausdinkRaides(rd);
        name.c_str();

        char* ch=new char[name.length()+1];
        strcpy(name.c_str(),ch);
        raide14->value(ch[0]);


       /* string zodis_4;
        char word_4[10];
        konvertavimas_4(zodis_4,word_4);
	    raide14->value(word_4[0]);
	    */


		raide24 = new Fl_Output(320, 190, 30, 30);//2 spejimo raide
		raide24->color((Fl_Color)246);

		raide34 = new Fl_Output(360, 190, 30, 30);//3 spejimo raide
		raide34->color((Fl_Color)246);

		raide44 = new Fl_Output(400, 190, 30, 30);//4 spejimo raide
		raide44->color((Fl_Color)246);

		new DrawHangman(10, 104, 215, 326);

		g3->end();
	}

	//žaidimas 5 raidem
	{
		g4 = new Fl_Group(-15, 13, 715, 532);
		g4->color((Fl_Color)246);
		uzrasas1 = new Fl_Box(195, 13, 295, 102, "KARTUV\304\226S"); //uzrasas KARTUVES
		uzrasas1->labeltype(FL_SHADOW_LABEL);
		uzrasas1->labelsize(49);

		tol1 = new Fl_Button(565, 505, 110, 30, "Toliau"); //mygtukas  toliau
		tol1->color((Fl_Color)55);
		tol1->selection_color(FL_GRAY0);
		tol1->labeltype(FL_EMBOSSED_LABEL);
		tol1->callback((Fl_Callback*)next_cb);
		tol1->labelcolor(FL_GRAY0);
		tol1->align(Fl_Align(FL_ALIGN_WRAP));


		ivesti1 = new Fl_Box(340, 259, 30, 16, "\304\256veskite raid\304\231"); //raides ivedimas uzrasas
		ivesti1->labeltype(FL_EMBOSSED_LABEL);
		ivesti1->labelsize(25);

		raidein = new Fl_Input(285, 296, 150, 29);  //ivedimo langelis

		spej1 = new Fl_Box(85, 448, 35, 17, "Liko sp\304\227jim\305\263:"); //liko spejimu uzrasas
		spej1->labelsize(20);

		rez1 = new Fl_Box(305, 448, 35, 17, "Rezultas:"); //rezultatas uzrasas
		rez1->labelsize(20);

		rezout1 = new Fl_Output(285, 475, 70, 35); //rezultato outputas
		rezout1->color((Fl_Color)246);

		spejout1 = new Fl_Output(75, 475, 70, 35);//spejimo outputas
		spejout1->color((Fl_Color)246);

		wraid1 = new Fl_Output(560, 400, 30, 30); // w raide
		wraid1->color((Fl_Color)246);
		wraid1->insert("w");

		vraid1 = new Fl_Output(525, 400, 30, 30); //v raide
		vraid1->color((Fl_Color)246);
		vraid1->insert("v");

		uraid1 = new Fl_Output(490, 400, 30, 30);//u raide
		uraid1->color((Fl_Color)246);
		uraid1->insert("u");

		oraid1 = new Fl_Output(280, 400, 30, 30); //o raide
		oraid1->color((Fl_Color)246);
		oraid1->insert("o");

		praid1 = new Fl_Output(315, 400, 30, 30); // p raide
		praid1->color((Fl_Color)246);
		praid1->insert("p");

		rraid1 = new Fl_Output(385, 400, 30, 30); // r raide
		rraid1->color((Fl_Color)246);
		rraid1->insert("r");

		sraid1 = new Fl_Output(420, 400, 30, 30); //s raide
		sraid1->color((Fl_Color)246);
		sraid1->insert("s");

		traid1 = new Fl_Output(455, 400, 30, 30); //t raide
		traid1->color((Fl_Color)246);
		traid1->insert("t");

		qraid1 = new Fl_Output(350, 400, 30, 30); //q raide
		qraid1->color((Fl_Color)246);
		qraid1->insert("q");

		yraid1 = new Fl_Output(630, 400, 30, 30); //y raide
		yraid1->color((Fl_Color)246);
		yraid1->insert("y");

		eraid1 = new Fl_Output(385, 365, 30, 30); // e raide
		eraid1->color((Fl_Color)246);
		eraid1->insert("e");

		graid1 = new Fl_Output(455, 365, 30, 30); //f raide
		graid1->color((Fl_Color)246);
		graid1->insert("g");

		hraid1 = new Fl_Output(490, 365, 30, 30); //h raide
		hraid1->color((Fl_Color)246);
		hraid1->insert("h");

		xraid1 = new Fl_Output(595, 400, 30, 30); //x raide
		xraid1->color((Fl_Color)246);
		xraid1->insert("x");

		nraid1 = new Fl_Output(245, 400, 30, 30);//n raide
		nraid1->color((Fl_Color)246);
		nraid1->insert("n");

		zraid1 = new Fl_Output(665, 400, 30, 30); // z raide
		zraid1->color((Fl_Color)246);
		zraid1->insert("z");

		mraid1 = new Fl_Output(665, 365, 30, 30); // m raide
		mraid1->color((Fl_Color)246);
		mraid1->insert("m");

		araid1 = new Fl_Output(245, 365, 30, 30); //a raide
		araid1->color((Fl_Color)246);
		araid1->insert("a");

		braid1 = new Fl_Output(280, 365, 30, 30); //b raide
		braid1->color((Fl_Color)246);
		braid1->insert("b");

		craid1 = new Fl_Output(315, 365, 30, 30); //c raide
		craid1->color((Fl_Color)246);
		craid1->insert("c");

		draid1 = new Fl_Output(350, 365, 30, 30); //d raide
		draid1->color((Fl_Color)246);
		draid1->insert("d");

		fraide = new Fl_Output(420, 365, 30, 30); // f raide
		fraide->color((Fl_Color)246);
		fraide->insert("f");

		iraid1 = new Fl_Output(525, 365, 30, 30);//i raide
		iraid1->color((Fl_Color)246);
		iraid1->insert("i");

		jraid1 = new Fl_Output(560, 365, 30, 30); // j raide
		jraid1->color((Fl_Color)246);
		jraid1->insert("j");

		kraid1 = new Fl_Output(595, 365, 30, 30); // k raide
		kraid1->color((Fl_Color)246);
		kraid1->insert("k");

		lraid1 = new Fl_Output(630, 365, 30, 30); //l raide
		lraid1->color((Fl_Color)246);
		lraid1->insert("l");

		pirmspej1 = new Fl_Output(280, 190, 30, 30); //1 spejama raide
		pirmspej1->color((Fl_Color)246);

		antraspej1 = new Fl_Output(320, 190, 30, 30); //2 spejama raide
		antraspej1->color((Fl_Color)246);

	    treciaspej1 = new Fl_Output(360, 190, 30, 30);//3 spejama raide
		treciaspej1->color((Fl_Color)246);

		ketvirtaspej1 = new Fl_Output(400, 190, 30, 30);//4 spejama raide
		ketvirtaspej1->color((Fl_Color)246);

		penktaspej1 = new Fl_Output(440, 190, 30, 30);//5 spejama raide
		penktaspej1->color((Fl_Color)246);

		new DrawHangman(10, 104, 215, 326);

		g4->end();
	}
	//zaidimas, kai zodzio sunkumas 7 raides
	{
		g5 = new Fl_Group(-15, 13, 715, 532);
		g5->color((Fl_Color)246);

		uzrasas = new Fl_Box(195, 13, 295, 102, "KARTUV\304\226S"); //uzrasas KARTUVES
		uzrasas->labeltype(FL_SHADOW_LABEL);
		uzrasas->labelsize(49);

		tol = new Fl_Button(565, 505, 110, 30, "Toliau"); //mygtukas  toliau
		tol->color((Fl_Color)55);
		tol->selection_color(FL_GRAY0);
		tol->labeltype(FL_EMBOSSED_LABEL);
		tol->callback((Fl_Callback*)next_cb);
		tol->labelcolor(FL_GRAY0);
		tol->align(Fl_Align(FL_ALIGN_WRAP));

		ivesti = new Fl_Box(340, 259, 30, 16, "\304\256veskite raid\304\231"); //raides ivedimas uzrasas
		ivesti->labeltype(FL_EMBOSSED_LABEL);
		ivesti->labelsize(25);

		raideinn = new Fl_Input(285, 296, 150, 29);  //ivedimo langelis

		spej = new Fl_Box(85, 448, 35, 17, "Liko sp\304\227jim\305\263:"); //liko spejimu uzrasas
		spej->labelsize(20);

		rez = new Fl_Box(305, 448, 35, 17, "Rezultas:"); //rezultatas uzrasas
		rez->labelsize(20);

		rezout = new Fl_Output(285, 475, 70, 35); //rezultato outputas
		rezout->color((Fl_Color)246);

		spejout = new Fl_Output(75, 475, 70, 35);//spejimo outputas
		spejout->color((Fl_Color)246);

		wraid = new Fl_Output(560, 400, 30, 30); // w raide
		wraid->color((Fl_Color)246);
		wraid->insert("w");

		vraid = new Fl_Output(525, 400, 30, 30); //v raide
		vraid->color((Fl_Color)246);
		vraid->insert("v");

		uraid = new Fl_Output(490, 400, 30, 30);//u raide
		uraid->color((Fl_Color)246);
		uraid->insert("u");

		oraid = new Fl_Output(280, 400, 30, 30); //o raide
		oraid->color((Fl_Color)246);
		oraid->insert("o");

		praid = new Fl_Output(315, 400, 30, 30); // p raide
		praid->color((Fl_Color)246);
		praid->insert("p");

		rraid = new Fl_Output(385, 400, 30, 30); // r raide
		rraid->color((Fl_Color)246);
		rraid->insert("r");

		sraid = new Fl_Output(420, 400, 30, 30); //s raide
		sraid->color((Fl_Color)246);
		sraid->insert("s");

		traid = new Fl_Output(455, 400, 30, 30); //t raide
		traid->color((Fl_Color)246);
		traid->insert("t");

		qraid = new Fl_Output(350, 400, 30, 30); //q raide
		qraid->color((Fl_Color)246);
		qraid->insert("q");

		yraid = new Fl_Output(630, 400, 30, 30); //y raide
		yraid->color((Fl_Color)246);
		yraid->insert("y");

		eraid = new Fl_Output(385, 365, 30, 30); // e raide
		eraid->color((Fl_Color)246);
		eraid->insert("e");

		graid = new Fl_Output(455, 365, 30, 30); //g raide
		graid->color((Fl_Color)246);
		graid->insert("g");

		hraid = new Fl_Output(490, 365, 30, 30); //h raide
		hraid->color((Fl_Color)246);
		hraid->insert("h");

		xraid = new Fl_Output(595, 400, 30, 30); //x raide
		xraid->color((Fl_Color)246);
		xraid->insert("x");

		nraid = new Fl_Output(245, 400, 30, 30);//n raide
		nraid->color((Fl_Color)246);
		nraid->insert("n");

		zraid = new Fl_Output(665, 400, 30, 30); // z raide
		zraid->color((Fl_Color)246);
		zraid->insert("z");

		mraid = new Fl_Output(665, 365, 30, 30); // m raide
		mraid->color((Fl_Color)246);
		mraid->insert("m");

		araid = new Fl_Output(245, 365, 30, 30); //a raide
		araid->color((Fl_Color)246);
		araid->insert("a");

		braid = new Fl_Output(280, 365, 30, 30); //b raide
		braid->color((Fl_Color)246);
		braid->insert("b");

		craid = new Fl_Output(315, 365, 30, 30); //c raide
		craid->color((Fl_Color)246);
		craid->insert("c");

		draid = new Fl_Output(350, 365, 30, 30); //d raide
		draid->color((Fl_Color)246);
		draid->insert("d");

		fraid = new Fl_Output(420, 365, 30, 30); // f raide
		fraid->color((Fl_Color)246);
		fraid->insert("f");

		iraid = new Fl_Output(525, 365, 30, 30);//i raide
		iraid->color((Fl_Color)246);
		iraid->insert("i");

		jraid = new Fl_Output(560, 365, 30, 30); // j raide
		jraid->color((Fl_Color)246);
		jraid->insert("j");

		kraid = new Fl_Output(595, 365, 30, 30); // k raide
		kraid->color((Fl_Color)246);
		kraid->insert("k");

		lraid = new Fl_Output(630, 365, 30, 30); //l raide
		lraid->color((Fl_Color)246);
		lraid->insert("l");

		pirmspej = new Fl_Output(280, 190, 30, 30); //1 spejama raide
		pirmspej->color((Fl_Color)246);

		antraspej = new Fl_Output(320, 190, 30, 30); //2 spejama raide
		antraspej->color((Fl_Color)246);

		treciaspej = new Fl_Output(360, 190, 30, 30);//3 spejama raide
		treciaspej->color((Fl_Color)246);

		ketvirtaspej = new Fl_Output(400, 190, 30, 30);//4 spejama raide
		ketvirtaspej->color((Fl_Color)246);

		penktaspej = new Fl_Output(440, 190, 30, 30);//5 spejama raide
		penktaspej->color((Fl_Color)246);

		sestaspej = new Fl_Output(480, 190, 30, 30); //6 spejama raide
		sestaspej->color((Fl_Color)246);

		septintaspej = new Fl_Output(520, 190, 30, 30); //7 spejama raide
		septintaspej->color((Fl_Color)246);

		new DrawHangman(10, 104, 215, 326);

		g5->end();
	}
	//Laimejote!
	{
		g6 = new Fl_Group(0, 0, 715, 555);
		g6->color((Fl_Color)246);

		z = new Fl_Box(145, 38, 445, 97, "Laim\304\227jote!");
		z->labeltype(FL_EMBOSSED_LABEL);
		z->labelsize(50);

		top = new Fl_Button(235, 330, 270, 70, "Geriausi\305\263 \305\276""aid\304\227j\305\263 lentel\304\227");
		top->color((Fl_Color)55);
		top->selection_color(FL_GRAY0);
		top->labeltype(FL_EMBOSSED_LABEL);
		top->labelsize(20);
		top->labelcolor(FL_GRAY0);
		top->callback(geriausiulentele_cb);

		contin = new Fl_Button(260, 240, 220, 70, "T\304\231sti");
		contin->color((Fl_Color)55);
		contin->selection_color(FL_GRAY0);
		contin->labeltype(FL_EMBOSSED_LABEL);
		contin->labelsize(20);
		contin->labelcolor(FL_GRAY0);

		iseiti = new Fl_Button(260, 420, 220, 70, "I\305\241""eiti i\305\241 \305\276""aidimo");
		iseiti->color((Fl_Color)55);
		iseiti->selection_color(FL_GRAY0);
		iseiti->labeltype(FL_EMBOSSED_LABEL);
		iseiti->labelsize(20);
		iseiti->labelcolor(FL_GRAY0);
		iseiti->callback((Fl_Callback*)done_cb);
		iseiti->align(Fl_Align(FL_ALIGN_WRAP));

		result1 = new Fl_Box(260, 142, 180, 73, "rezultatas:");
		result1->labeltype(FL_EMBOSSED_LABEL);
		result1->labelsize(25);
		lala = new Fl_Output(425, 160, 120, 35);

		task = new Fl_Output(175, 160, 100, 35);
		task->color((Fl_Color)246);
		task->labelsize(25);
		g6->end();
	}


	//pralaimejote
	{
		g7 = new Fl_Group(0, 0, 715, 555);
		g7->color((Fl_Color)246);

		yy = new Fl_Box(130, 34, 465, 96, "Pralaim\304\227jote :(");
		yy->labeltype(FL_EMBOSSED_LABEL);
		yy->labelsize(50);
		yy->align(Fl_Align(FL_ALIGN_WRAP));

		xx = new Fl_Button(245, 190, 220, 70, "Prad\304\227ti i\305\241 naujo");
		xx->color((Fl_Color)55);
		xx->selection_color(FL_GRAY0);
		xx->labeltype(FL_EMBOSSED_LABEL);
		xx->labelsize(20);
		xx->labelcolor(FL_GRAY0);
		xx->callback((Fl_Callback*)isnaujo_cb);

		ww = new Fl_Button(245, 310, 220, 70, "I\305\241""eiti i\305\241 \305\276""aidimo");
		ww->color((Fl_Color)55);
		ww->selection_color(FL_GRAY0);
		ww->labeltype(FL_EMBOSSED_LABEL);
		ww->callback((Fl_Callback*)done_cb);
		ww->labelsize(20);
		ww->labelcolor(FL_GRAY0);
		g7->end();
	}


	//geriausiu zaideju lentele
	{
		g8 = new Fl_Group(0, 0, 715, 555);
		g8->color((Fl_Color)246);

		vv = new Fl_Box(125, 9, 465, 96, "Geriausi\305\263 \305\276""aid\304\227j\305\263 lentel\304\227");
		vv->labeltype(FL_EMBOSSED_LABEL);
		vv->labelsize(50);
		vv->align(Fl_Align(FL_ALIGN_WRAP));

		uu = new Fl_Box(20, 168, 675, 322, "label");
		uu->box(FL_FLAT_BOX);
		uu->color((Fl_Color)55);
		uu->labeltype(FL_NO_LABEL);

		tt = new Fl_Output(75, 181, 190, 29);
		tt->labeltype(FL_NO_LABEL);

		ss = new Fl_Box(5, 128, 240, 47, "Vardas");
		ss->labeltype(FL_SHADOW_LABEL);
		ss->labelsize(26);

		rr = new Fl_Box(420, 128, 240, 47, "Rezultatas");
		rr->labeltype(FL_SHADOW_LABEL);
		rr->labelsize(26);

		qq = new Fl_Box(35, 223, 25, 212, "1.        2.         3.  4.  5.  6.  7.  8.  9.  10.");
		qq->labelsize(26);
		qq->align(Fl_Align(FL_ALIGN_WRAP));

		pp = new Fl_Output(75, 211, 190, 29);
		pp->labeltype(FL_NO_LABEL);

		oo = new Fl_Output(75, 241, 190, 29);
		oo->labeltype(FL_NO_LABEL);

		nn = new Fl_Output(75, 271, 190, 28);
		nn->labeltype(FL_NO_LABEL);

		mm = new Fl_Output(75, 301, 190, 29);
		mm->labeltype(FL_NO_LABEL);

		ll = new Fl_Output(75, 331, 190, 29);
		ll->labeltype(FL_NO_LABEL);

		kk = new Fl_Output(75, 361, 190, 29);
		kk->labeltype(FL_NO_LABEL);

		jj = new Fl_Output(75, 391, 190, 29);
		jj->labeltype(FL_NO_LABEL);

		ii = new Fl_Output(75, 421, 190, 29);
		ii->labeltype(FL_NO_LABEL);

		hh = new Fl_Output(75, 451, 190, 29);
		hh->labeltype(FL_NO_LABEL);

	    gg = new Fl_Output(485, 181, 120, 29);
		gg->labeltype(FL_NO_LABEL);

		ff = new Fl_Output(485, 211, 120, 29);
		ff->labeltype(FL_NO_LABEL);

		ee = new Fl_Output(485, 241, 120, 29);
		ee->labeltype(FL_NO_LABEL);

		dd = new Fl_Output(485, 271, 120, 29);
		dd->labeltype(FL_NO_LABEL);

		cc = new Fl_Output(485, 301, 120, 29);
		cc->labeltype(FL_NO_LABEL);

		bb = new Fl_Output(485, 331, 120, 29);
		bb->labeltype(FL_NO_LABEL);

		aa = new Fl_Output(485, 361, 120, 29);
		aa->labeltype(FL_NO_LABEL);

		zzz = new Fl_Output(485, 391, 120, 29);
		zzz->labeltype(FL_NO_LABEL);

		yyy = new Fl_Output(485, 421, 120, 29);
		yyy->labeltype(FL_NO_LABEL);

		xxx = new Fl_Output(485, 451, 120, 29);
		xxx->labeltype(FL_NO_LABEL);

		vvv = new Fl_Button(585, 500, 110, 30, "Gr\304\257\305\276ti");
		vvv->color((Fl_Color)55);
		vvv->selection_color(FL_GRAY0);
		vvv->labeltype(FL_EMBOSSED_LABEL);
		vvv->callback(geriausiulentelegrizti_cb);
		vvv->labelcolor(FL_GRAY0);
		vvv->align(Fl_Align(FL_ALIGN_WRAP));

		g8->end();
	}

	G_wiz->end();
	G_win->end();
	G_win->show(argc, argv);


	return Fl::run();
}
